CREATE TABLE IF NOT EXISTS official_codes (
    code TEXT PRIMARY KEY,
    title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS official_law_toc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    law_code TEXT NOT NULL REFERENCES official_codes(code) ON DELETE CASCADE,
    division TEXT,
    title_num TEXT,
    part_num TEXT,
    chapter_num TEXT,
    article_num TEXT,
    heading TEXT NOT NULL,
    active_flg TEXT,
    trans_uid TEXT,
    trans_update TIMESTAMP,
    node_sequence INTEGER,
    node_level INTEGER,
    node_position INTEGER,
    node_treepath TEXT NOT NULL,
    contains_law_sections TEXT,
    history_note TEXT,
    op_statutes TEXT,
    op_chapter TEXT,
    op_section TEXT,
    UNIQUE (law_code, node_treepath)
);

CREATE INDEX IF NOT EXISTS idx_official_law_toc_hierarchy
    ON official_law_toc (law_code, division, title_num, part_num, chapter_num, article_num);

CREATE INDEX IF NOT EXISTS idx_official_law_toc_tree
    ON official_law_toc (law_code, node_treepath);

CREATE TABLE IF NOT EXISTS official_law_toc_sections (
    id TEXT PRIMARY KEY,
    law_code TEXT NOT NULL REFERENCES official_codes(code) ON DELETE CASCADE,
    node_treepath TEXT NOT NULL,
    section_num TEXT NOT NULL,
    section_order INTEGER,
    title_text TEXT,
    op_statutes TEXT,
    op_chapter TEXT,
    op_section TEXT,
    trans_uid TEXT,
    trans_update TIMESTAMP,
    law_section_version_id TEXT,
    seq_num INTEGER
);

CREATE INDEX IF NOT EXISTS idx_official_law_toc_sections_lookup
    ON official_law_toc_sections (law_code, node_treepath, section_num);

CREATE INDEX IF NOT EXISTS idx_official_law_toc_sections_section
    ON official_law_toc_sections (law_code, section_num);

CREATE TABLE IF NOT EXISTS official_law_sections (
    id TEXT PRIMARY KEY,
    law_code TEXT NOT NULL REFERENCES official_codes(code) ON DELETE CASCADE,
    section_num TEXT NOT NULL,
    op_statutes TEXT,
    op_chapter TEXT,
    op_section TEXT,
    effective_date TIMESTAMP,
    law_section_version_id TEXT,
    division TEXT,
    title_num TEXT,
    part_num TEXT,
    chapter_num TEXT,
    article_num TEXT,
    history TEXT,
    content_xml TEXT NOT NULL,
    content_text TEXT NOT NULL,
    active_flg TEXT,
    trans_uid TEXT,
    trans_update TIMESTAMP,
    display_url TEXT GENERATED ALWAYS AS (
        'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=' || law_code || '&sectionNum=' || section_num
    ) STORED,
    search_vector tsvector GENERATED ALWAYS AS (
        to_tsvector(
            'english',
            COALESCE(law_code, '') || ' ' ||
            COALESCE(section_num, '') || ' ' ||
            COALESCE(division, '') || ' ' ||
            COALESCE(title_num, '') || ' ' ||
            COALESCE(part_num, '') || ' ' ||
            COALESCE(chapter_num, '') || ' ' ||
            COALESCE(article_num, '') || ' ' ||
            COALESCE(history, '') || ' ' ||
            COALESCE(content_text, '')
        )
    ) STORED
);

CREATE INDEX IF NOT EXISTS idx_official_law_sections_hierarchy
    ON official_law_sections (law_code, division, title_num, part_num, chapter_num, article_num);

CREATE INDEX IF NOT EXISTS idx_official_law_sections_section
    ON official_law_sections (law_code, section_num);

CREATE INDEX IF NOT EXISTS idx_official_law_sections_active
    ON official_law_sections (active_flg);

CREATE INDEX IF NOT EXISTS idx_official_law_sections_search
    ON official_law_sections USING GIN (search_vector);

CREATE OR REPLACE VIEW law_section_search AS
WITH headings AS (
    SELECT
        s.id,
        div.heading AS division_heading,
        tit.heading AS title_heading,
        part.heading AS part_heading,
        chap.heading AS chapter_heading,
        art.heading AS article_heading
    FROM official_law_sections s
    LEFT JOIN LATERAL (
        SELECT t.heading
        FROM official_law_toc t
        WHERE t.law_code = s.law_code
          AND t.division IS NOT DISTINCT FROM s.division
          AND t.title_num IS NULL
          AND t.part_num IS NULL
          AND t.chapter_num IS NULL
          AND t.article_num IS NULL
        ORDER BY t.node_sequence
        LIMIT 1
    ) div ON TRUE
    LEFT JOIN LATERAL (
        SELECT t.heading
        FROM official_law_toc t
        WHERE t.law_code = s.law_code
          AND t.division IS NOT DISTINCT FROM s.division
          AND t.title_num IS NOT DISTINCT FROM s.title_num
          AND t.part_num IS NULL
          AND t.chapter_num IS NULL
          AND t.article_num IS NULL
          AND s.title_num IS NOT NULL
        ORDER BY t.node_sequence
        LIMIT 1
    ) tit ON TRUE
    LEFT JOIN LATERAL (
        SELECT t.heading
        FROM official_law_toc t
        WHERE t.law_code = s.law_code
          AND t.division IS NOT DISTINCT FROM s.division
          AND t.title_num IS NOT DISTINCT FROM s.title_num
          AND t.part_num IS NOT DISTINCT FROM s.part_num
          AND t.chapter_num IS NULL
          AND t.article_num IS NULL
          AND s.part_num IS NOT NULL
        ORDER BY t.node_sequence
        LIMIT 1
    ) part ON TRUE
    LEFT JOIN LATERAL (
        SELECT t.heading
        FROM official_law_toc t
        WHERE t.law_code = s.law_code
          AND t.division IS NOT DISTINCT FROM s.division
          AND t.title_num IS NOT DISTINCT FROM s.title_num
          AND t.part_num IS NOT DISTINCT FROM s.part_num
          AND t.chapter_num IS NOT DISTINCT FROM s.chapter_num
          AND t.article_num IS NULL
          AND s.chapter_num IS NOT NULL
        ORDER BY t.node_sequence
        LIMIT 1
    ) chap ON TRUE
    LEFT JOIN LATERAL (
        SELECT t.heading
        FROM official_law_toc t
        WHERE t.law_code = s.law_code
          AND t.division IS NOT DISTINCT FROM s.division
          AND t.title_num IS NOT DISTINCT FROM s.title_num
          AND t.part_num IS NOT DISTINCT FROM s.part_num
          AND t.chapter_num IS NOT DISTINCT FROM s.chapter_num
          AND t.article_num IS NOT DISTINCT FROM s.article_num
          AND s.article_num IS NOT NULL
        ORDER BY t.node_sequence
        LIMIT 1
    ) art ON TRUE
)
SELECT
    s.id AS law_section_id,
    s.law_code,
    c.title AS code_title,
    s.law_code || ' ' || s.section_num AS citation,
    s.section_num,
    s.division,
    s.title_num,
    s.part_num,
    s.chapter_num,
    s.article_num,
    h.division_heading,
    h.title_heading,
    h.part_heading,
    h.chapter_heading,
    h.article_heading,
    concat_ws(' > ', h.division_heading, h.title_heading, h.part_heading, h.chapter_heading, h.article_heading) AS hierarchy_path,
    s.history,
    s.content_text,
    s.content_xml,
    s.active_flg,
    s.effective_date,
    s.display_url,
    s.search_vector
FROM official_law_sections s
JOIN official_codes c
  ON c.code = s.law_code
JOIN headings h
  ON h.id = s.id;

CREATE OR REPLACE VIEW section_search AS
SELECT
    law_section_id AS section_id,
    law_code AS code_abbrev,
    code_title AS code_name,
    citation,
    section_num AS section_number,
    NULL::TEXT AS heading,
    division_heading AS division_name,
    chapter_heading AS chapter_name,
    article_heading AS article_name,
    hierarchy_path,
    display_url,
    display_url AS source_page_url,
    content_text AS body_text,
    history AS history_text,
    1::INTEGER AS source_count,
    search_vector,
    division,
    title_num,
    part_num,
    chapter_num,
    article_num,
    active_flg,
    effective_date
FROM law_section_search;

CREATE OR REPLACE VIEW law_section_embedding_input AS
SELECT
    law_section_id,
    citation,
    law_code,
    code_title,
    division,
    title_num,
    part_num,
    chapter_num,
    article_num,
    hierarchy_path,
    concat_ws(
        ' ',
        citation,
        code_title,
        hierarchy_path,
        history,
        content_text
    ) AS semantic_text
FROM law_section_search;

CREATE OR REPLACE VIEW law_toc_branch_sections AS
SELECT
    t.law_code,
    t.node_treepath,
    t.node_level,
    t.node_sequence,
    t.heading AS branch_heading,
    t.division,
    t.title_num,
    t.part_num,
    t.chapter_num,
    t.article_num,
    s.law_section_id,
    s.citation,
    s.section_num,
    s.hierarchy_path,
    s.content_text,
    s.history,
    s.active_flg,
    s.display_url
FROM official_law_toc t
JOIN official_law_toc_sections ts
  ON ts.law_code = t.law_code
 AND ts.node_treepath = t.node_treepath
JOIN law_section_search s
  ON s.law_code = ts.law_code
 AND s.section_num = ts.section_num;
